#!/usr/bin/env bash
# Generate windows/git-aliases.ps1 from the oh-my-zsh git plugin, so the PowerShell
# setup gets the same gst/gco/gp/... aliases as zsh. Re-run after omz updates.
# Usage: windows/gen-git-aliases.sh [path-to-git.plugin.zsh] [out.ps1]
set -euo pipefail
plugin="${1:-$HOME/.oh-my-zsh/plugins/git/git.plugin.zsh}"
out="${2:-$(dirname "$0")/git-aliases.ps1}"
[ -f "$plugin" ] || { echo "omz git plugin not found: $plugin" >&2; exit 1; }

re="^alias ([A-Za-z_][A-Za-z0-9_]*)='(git .*)'$"
names=(); defs=""; skipped=""
while IFS= read -r line; do
  [[ "$line" =~ $re ]] || continue
  name="${BASH_REMATCH[1]}"; body="${BASH_REMATCH[2]}"
  # skip multi-statement / piped / redirected bodies - port those by hand if wanted
  case "$body" in *";"*|*"&&"*|*"|"*|*"<"*|*'"'*) skipped+=" $name"; continue ;; esac
  # omz subshell helpers -> PS helpers
  body="${body//\$(git_current_branch)/\$(Get-GitCurrentBranch)}"
  body="${body//\$(git_main_branch)/\$(Get-GitMainBranch)}"
  body="${body//\$(git_develop_branch)/\$(Get-GitDevelopBranch)}"
  # any $() we didn't translate -> skip to avoid emitting broken PS
  case "$body" in *'$('*) case "$body" in *'Get-Git'*) : ;; *) skipped+=" $name"; continue ;; esac ;; esac
  # git's @{upstream}/@{push} ref syntax collides with PS @{} hash literals -> quote it
  body="$(printf '%s' "$body" | sed -E "s/@\{[^}]*\}/'&'/g")"
  names+=("$name")
  defs+="function ${name} { git ${body#git } @args }"$'\n'
done < "$plugin"

{
  echo "# git-aliases.ps1 - GENERATED by windows/gen-git-aliases.sh from the oh-my-zsh"
  echo "# git plugin. Do not edit by hand; re-run the generator. Dot-sourced by the profile."
  echo "# ${#names[@]} aliases ported. Skipped (multi-command/quoted, add by hand if needed):"
  echo "#  ${skipped# }"
  echo
  echo "# omz branch helpers"
  echo 'function Get-GitCurrentBranch { git branch --show-current 2>$null }'
  echo 'function Get-GitMainBranch { foreach ($b in "main","trunk","master") { if (git show-ref --verify --quiet "refs/heads/$b") { return $b } }; return "main" }'
  echo 'function Get-GitDevelopBranch { foreach ($b in "dev","devel","develop","development") { if (git show-ref --verify --quiet "refs/heads/$b") { return $b } }; return "develop" }'
  echo
  echo "# free the names that collide with built-in PowerShell aliases (gc/gp/gl/gm/gcm...)"
  printf 'foreach ($n in @(%s)) { if (Test-Path "Alias:$n") { Remove-Item "Alias:$n" -Force -ErrorAction SilentlyContinue } }\n' \
    "$(printf "'%s'," "${names[@]}" | sed 's/,$//')"
  echo
  echo "# aliases"
  printf '%s' "$defs"
} > "$out"
echo "wrote $out (${#names[@]} aliases, skipped:${skipped:- none})"
