# git-aliases.ps1 - GENERATED by windows/gen-git-aliases.sh from the oh-my-zsh
# git plugin. Do not edit by hand; re-run the generator. Dot-sourced by the profile.
# 160 aliases ported. Skipped (multi-command/quoted, add by hand if needed):
#  gwip gdct glods glod glola glols glol gignored gfg ggpull gpoat ggpush gpristine gwipe gunwip gtv

# omz branch helpers
function Get-GitCurrentBranch { git branch --show-current 2>$null }
function Get-GitMainBranch { foreach ($b in "main","trunk","master") { if (git show-ref --verify --quiet "refs/heads/$b") { return $b } }; return "main" }
function Get-GitDevelopBranch { foreach ($b in "dev","devel","develop","development") { if (git show-ref --verify --quiet "refs/heads/$b") { return $b } }; return "develop" }

# free the names that collide with built-in PowerShell aliases (gc/gp/gl/gm/gcm...)
foreach ($n in @('ga','gaa','gapa','gau','gav','gam','gama','gamc','gamscp','gams','gap','gapt','gbs','gbsb','gbsg','gbsn','gbso','gbsr','gbss','gbl','gb','gba','gbd','gbD','gbm','gbnm','gbr','ggsup','gco','gcor','gcb','gcB','gcd','gcm','gcp','gcpa','gcpc','gclean','gcl','gclf','gcam','gcas','gcasm','gcs','gcss','gcssm','gcmsg','gcsm','gc','gca','gcn','gcf','gcfu','gd','gdca','gdcw','gds','gdw','gdup','gdt','gf','gfo','gg','gga','ghh','glgg','glgga','glgm','glo','glog','gloga','glg','glgp','gm','gma','gmc','gmom','gmum','gmtl','gmtlvim','gl','gpr','gprv','gpra','gprav','gprom','gpromi','gprum','gprumi','gluc','glum','gp','gpd','gpsup','gpv','gpod','gpu','grb','grba','grbc','grbi','grbo','grbs','grbd','grbm','grbom','grbum','grf','gr','grv','gra','grrm','grmv','grset','grup','grh','gru','grhh','grhk','grhs','groh','grs','grss','grst','grev','greva','grevc','grm','grmc','gcount','gsh','gsps','gstall','gstaa','gstc','gstd','gstl','gstp','gsts','gst','gss','gsb','gsi','gsu','gsd','gsr','gsw','gswc','gswd','gswm','gta','gts','gignore','gunignore','gwch','gwt','gwta','gwtls','gwtmv','gwtrm')) { if (Test-Path "Alias:$n") { Remove-Item "Alias:$n" -Force -ErrorAction SilentlyContinue } }

# aliases
function ga { git add @args }
function gaa { git add --all @args }
function gapa { git add --patch @args }
function gau { git add --update @args }
function gav { git add --verbose @args }
function gam { git am @args }
function gama { git am --abort @args }
function gamc { git am --continue @args }
function gamscp { git am --show-current-patch @args }
function gams { git am --skip @args }
function gap { git apply @args }
function gapt { git apply --3way @args }
function gbs { git bisect @args }
function gbsb { git bisect bad @args }
function gbsg { git bisect good @args }
function gbsn { git bisect new @args }
function gbso { git bisect old @args }
function gbsr { git bisect reset @args }
function gbss { git bisect start @args }
function gbl { git blame -w @args }
function gb { git branch @args }
function gba { git branch --all @args }
function gbd { git branch --delete @args }
function gbD { git branch --delete --force @args }
function gbm { git branch --move @args }
function gbnm { git branch --no-merged @args }
function gbr { git branch --remote @args }
function ggsup { git branch --set-upstream-to=origin/$(Get-GitCurrentBranch) @args }
function gco { git checkout @args }
function gcor { git checkout --recurse-submodules @args }
function gcb { git checkout -b @args }
function gcB { git checkout -B @args }
function gcd { git checkout $(Get-GitDevelopBranch) @args }
function gcm { git checkout $(Get-GitMainBranch) @args }
function gcp { git cherry-pick @args }
function gcpa { git cherry-pick --abort @args }
function gcpc { git cherry-pick --continue @args }
function gclean { git clean --interactive -d @args }
function gcl { git clone --recurse-submodules @args }
function gclf { git clone --recursive --shallow-submodules --filter=blob:none --also-filter-submodules @args }
function gcam { git commit --all --message @args }
function gcas { git commit --all --signoff @args }
function gcasm { git commit --all --signoff --message @args }
function gcs { git commit --gpg-sign @args }
function gcss { git commit --gpg-sign --signoff @args }
function gcssm { git commit --gpg-sign --signoff --message @args }
function gcmsg { git commit --message @args }
function gcsm { git commit --signoff --message @args }
function gc { git commit --verbose @args }
function gca { git commit --verbose --all @args }
function gcn { git commit --verbose --no-edit @args }
function gcf { git config --list @args }
function gcfu { git commit --fixup @args }
function gd { git diff @args }
function gdca { git diff --cached @args }
function gdcw { git diff --cached --word-diff @args }
function gds { git diff --staged @args }
function gdw { git diff --word-diff @args }
function gdup { git diff '@{upstream}' @args }
function gdt { git diff-tree --no-commit-id --name-only -r @args }
function gf { git fetch @args }
function gfo { git fetch origin @args }
function gg { git gui citool @args }
function gga { git gui citool --amend @args }
function ghh { git help @args }
function glgg { git log --graph @args }
function glgga { git log --graph --decorate --all @args }
function glgm { git log --graph --max-count=10 @args }
function glo { git log --oneline --decorate @args }
function glog { git log --oneline --decorate --graph @args }
function gloga { git log --oneline --decorate --graph --all @args }
function glg { git log --stat @args }
function glgp { git log --stat --patch @args }
function gm { git merge @args }
function gma { git merge --abort @args }
function gmc { git merge --continue @args }
function gmom { git merge origin/$(Get-GitMainBranch) @args }
function gmum { git merge upstream/$(Get-GitMainBranch) @args }
function gmtl { git mergetool --no-prompt @args }
function gmtlvim { git mergetool --no-prompt --tool=vimdiff @args }
function gl { git pull @args }
function gpr { git pull --rebase @args }
function gprv { git pull --rebase -v @args }
function gpra { git pull --rebase --autostash @args }
function gprav { git pull --rebase --autostash -v @args }
function gprom { git pull --rebase origin $(Get-GitMainBranch) @args }
function gpromi { git pull --rebase=interactive origin $(Get-GitMainBranch) @args }
function gprum { git pull --rebase upstream $(Get-GitMainBranch) @args }
function gprumi { git pull --rebase=interactive upstream $(Get-GitMainBranch) @args }
function gluc { git pull upstream $(Get-GitCurrentBranch) @args }
function glum { git pull upstream $(Get-GitMainBranch) @args }
function gp { git push @args }
function gpd { git push --dry-run @args }
function gpsup { git push --set-upstream origin $(Get-GitCurrentBranch) @args }
function gpv { git push --verbose @args }
function gpod { git push origin --delete @args }
function gpu { git push upstream @args }
function grb { git rebase @args }
function grba { git rebase --abort @args }
function grbc { git rebase --continue @args }
function grbi { git rebase --interactive @args }
function grbo { git rebase --onto @args }
function grbs { git rebase --skip @args }
function grbd { git rebase $(Get-GitDevelopBranch) @args }
function grbm { git rebase $(Get-GitMainBranch) @args }
function grbom { git rebase origin/$(Get-GitMainBranch) @args }
function grbum { git rebase upstream/$(Get-GitMainBranch) @args }
function grf { git reflog @args }
function gr { git remote @args }
function grv { git remote --verbose @args }
function gra { git remote add @args }
function grrm { git remote remove @args }
function grmv { git remote rename @args }
function grset { git remote set-url @args }
function grup { git remote update @args }
function grh { git reset @args }
function gru { git reset -- @args }
function grhh { git reset --hard @args }
function grhk { git reset --keep @args }
function grhs { git reset --soft @args }
function groh { git reset origin/$(Get-GitCurrentBranch) --hard @args }
function grs { git restore @args }
function grss { git restore --source @args }
function grst { git restore --staged @args }
function grev { git revert @args }
function greva { git revert --abort @args }
function grevc { git revert --continue @args }
function grm { git rm @args }
function grmc { git rm --cached @args }
function gcount { git shortlog --summary --numbered @args }
function gsh { git show @args }
function gsps { git show --pretty=short --show-signature @args }
function gstall { git stash --all @args }
function gstaa { git stash apply @args }
function gstc { git stash clear @args }
function gstd { git stash drop @args }
function gstl { git stash list @args }
function gstp { git stash pop @args }
function gsts { git stash show --patch @args }
function gst { git status @args }
function gss { git status --short @args }
function gsb { git status --short --branch @args }
function gsi { git submodule init @args }
function gsu { git submodule update @args }
function gsd { git svn dcommit @args }
function gsr { git svn rebase @args }
function gsw { git switch @args }
function gswc { git switch --create @args }
function gswd { git switch $(Get-GitDevelopBranch) @args }
function gswm { git switch $(Get-GitMainBranch) @args }
function gta { git tag --annotate @args }
function gts { git tag --sign @args }
function gignore { git update-index --assume-unchanged @args }
function gunignore { git update-index --no-assume-unchanged @args }
function gwch { git log --patch --abbrev-commit --pretty=medium --raw @args }
function gwt { git worktree @args }
function gwta { git worktree add @args }
function gwtls { git worktree list @args }
function gwtmv { git worktree move @args }
function gwtrm { git worktree remove @args }
