# workspace binds 2-12 and 14-24, examples in hyprland.conf
bind = $mod, 2, workspace, 2
bind = $mod, 3, workspace, 3
bind = $mod, 4, workspace, 4
bind = $mod, 5, workspace, 5
bind = $mod, 6, workspace, 6
bind = $mod, 7, workspace, 7
bind = $mod, 8, workspace, 8
bind = $mod, 9, workspace, 9
bind = $mod, 0, workspace, 10
bind = $mod, minus, workspace, 11
bind = $mod, equal, workspace, 12
bind = $mod $alt, 2, workspace, 14
bind = $mod $alt, 3, workspace, 15
bind = $mod $alt, 4, workspace, 16
bind = $mod $alt, 5, workspace, 17
bind = $mod $alt, 6, workspace, 18
bind = $mod $alt, 7, workspace, 19
bind = $mod $alt, 8, workspace, 20
bind = $mod $alt, 9, workspace, 21
bind = $mod $alt, 0, workspace, 22
bind = $mod $alt, minus, workspace, 23
bind = $mod $alt, equal, workspace, 24
bind = $mod SHIFT, 2, movetoworkspace, 2
bind = $mod SHIFT, 3, movetoworkspace, 3
bind = $mod SHIFT, 4, movetoworkspace, 4
bind = $mod SHIFT, 5, movetoworkspace, 5
bind = $mod SHIFT, 6, movetoworkspace, 6
bind = $mod SHIFT, 7, movetoworkspace, 7
bind = $mod SHIFT, 8, movetoworkspace, 8
bind = $mod SHIFT, 9, movetoworkspace, 9
bind = $mod SHIFT, 0, movetoworkspace, 10
bind = $mod SHIFT, minus, movetoworkspace, 11
bind = $mod SHIFT, equal, movetoworkspace, 12
bind = $mod SHIFT $alt, 2, movetoworkspace, 14
bind = $mod SHIFT $alt, 3, movetoworkspace, 15
bind = $mod SHIFT $alt, 4, movetoworkspace, 16
bind = $mod SHIFT $alt, 5, movetoworkspace, 17
bind = $mod SHIFT $alt, 6, movetoworkspace, 18
bind = $mod SHIFT $alt, 7, movetoworkspace, 19
bind = $mod SHIFT $alt, 8, movetoworkspace, 20
bind = $mod SHIFT $alt, 9, movetoworkspace, 21
bind = $mod SHIFT $alt, 0, movetoworkspace, 22
bind = $mod SHIFT $alt, minus, movetoworkspace, 23
bind = $mod SHIFT $alt, equal, movetoworkspace, 24
