-- workspace ids interleave so primed sorts next to its partner:
-- N -> id 2N-1 (name N), primed N -> id 2N (name N')
for n = 1, 12 do
  hl.workspace_rule({ workspace = tostring(2 * n - 1), default_name = tostring(n) })
  hl.workspace_rule({ workspace = tostring(2 * n), default_name = tostring(n) .. "'" })
end

-- binds for 2-12 (the four N=1 examples live in hyprland.lua). Kept explicit,
-- not a loop, so the DMS mod+F1 cheatsheet parses every one.
hl.bind("SUPER + 2", hl.dsp.focus({ workspace = "3" }))
hl.bind("SUPER + ALT + 2", hl.dsp.focus({ workspace = "4" }))
hl.bind("SUPER + SHIFT + 2", hl.dsp.window.move({ workspace = "3" }))
hl.bind("SUPER + SHIFT + ALT + 2", hl.dsp.window.move({ workspace = "4" }))
hl.bind("SUPER + 3", hl.dsp.focus({ workspace = "5" }))
hl.bind("SUPER + ALT + 3", hl.dsp.focus({ workspace = "6" }))
hl.bind("SUPER + SHIFT + 3", hl.dsp.window.move({ workspace = "5" }))
hl.bind("SUPER + SHIFT + ALT + 3", hl.dsp.window.move({ workspace = "6" }))
hl.bind("SUPER + 4", hl.dsp.focus({ workspace = "7" }))
hl.bind("SUPER + ALT + 4", hl.dsp.focus({ workspace = "8" }))
hl.bind("SUPER + SHIFT + 4", hl.dsp.window.move({ workspace = "7" }))
hl.bind("SUPER + SHIFT + ALT + 4", hl.dsp.window.move({ workspace = "8" }))
hl.bind("SUPER + 5", hl.dsp.focus({ workspace = "9" }))
hl.bind("SUPER + ALT + 5", hl.dsp.focus({ workspace = "10" }))
hl.bind("SUPER + SHIFT + 5", hl.dsp.window.move({ workspace = "9" }))
hl.bind("SUPER + SHIFT + ALT + 5", hl.dsp.window.move({ workspace = "10" }))
hl.bind("SUPER + 6", hl.dsp.focus({ workspace = "11" }))
hl.bind("SUPER + ALT + 6", hl.dsp.focus({ workspace = "12" }))
hl.bind("SUPER + SHIFT + 6", hl.dsp.window.move({ workspace = "11" }))
hl.bind("SUPER + SHIFT + ALT + 6", hl.dsp.window.move({ workspace = "12" }))
hl.bind("SUPER + 7", hl.dsp.focus({ workspace = "13" }))
hl.bind("SUPER + ALT + 7", hl.dsp.focus({ workspace = "14" }))
hl.bind("SUPER + SHIFT + 7", hl.dsp.window.move({ workspace = "13" }))
hl.bind("SUPER + SHIFT + ALT + 7", hl.dsp.window.move({ workspace = "14" }))
hl.bind("SUPER + 8", hl.dsp.focus({ workspace = "15" }))
hl.bind("SUPER + ALT + 8", hl.dsp.focus({ workspace = "16" }))
hl.bind("SUPER + SHIFT + 8", hl.dsp.window.move({ workspace = "15" }))
hl.bind("SUPER + SHIFT + ALT + 8", hl.dsp.window.move({ workspace = "16" }))
hl.bind("SUPER + 9", hl.dsp.focus({ workspace = "17" }))
hl.bind("SUPER + ALT + 9", hl.dsp.focus({ workspace = "18" }))
hl.bind("SUPER + SHIFT + 9", hl.dsp.window.move({ workspace = "17" }))
hl.bind("SUPER + SHIFT + ALT + 9", hl.dsp.window.move({ workspace = "18" }))
hl.bind("SUPER + 0", hl.dsp.focus({ workspace = "19" }))
hl.bind("SUPER + ALT + 0", hl.dsp.focus({ workspace = "20" }))
hl.bind("SUPER + SHIFT + 0", hl.dsp.window.move({ workspace = "19" }))
hl.bind("SUPER + SHIFT + ALT + 0", hl.dsp.window.move({ workspace = "20" }))
hl.bind("SUPER + minus", hl.dsp.focus({ workspace = "21" }))
hl.bind("SUPER + ALT + minus", hl.dsp.focus({ workspace = "22" }))
hl.bind("SUPER + SHIFT + minus", hl.dsp.window.move({ workspace = "21" }))
hl.bind("SUPER + SHIFT + ALT + minus", hl.dsp.window.move({ workspace = "22" }))
hl.bind("SUPER + equal", hl.dsp.focus({ workspace = "23" }))
hl.bind("SUPER + ALT + equal", hl.dsp.focus({ workspace = "24" }))
hl.bind("SUPER + SHIFT + equal", hl.dsp.window.move({ workspace = "23" }))
hl.bind("SUPER + SHIFT + ALT + equal", hl.dsp.window.move({ workspace = "24" }))
